# Generated by Django 5.0.6 on 2024-06-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_authuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='nutrition_photos/')),
                ('description', models.TextField(max_length=2000)),
                ('trimester', models.PositiveIntegerField()),
            ],
        ),
    ]
