# Generated by Django 5.0.6 on 2024-06-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_nutritionadvice'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionadvice',
            name='week',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
