# Generated by Django 5.0.6 on 2024-06-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0008_authuser_groups_authuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='nutrition_photos/')),
                ('description', models.TextField(max_length=2000)),
                ('trimester', models.PositiveIntegerField()),
                ('week', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
